#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := tcp_server

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common /home/pedromonici/USP/IC/tcp_server/firewall /home/pedromonici/USP/IC/tcp_server/tflite-lib

include $(IDF_PATH)/make/project.mk
